; Shared defaults applied to every profile (overridden per profile when set).
; 128k == 131072
; 64k == 65536
; 32k == 32768
; 16k == 16384
; 8k == 8192
; 4k == 4096
; 2k == 2048
; 1k == 1024
[*]
t = 6
b = 2048
ub = 512
sleep-idle-seconds = 300
load-mode = mmap+mlock
flash-attn = true
ngl = 999
jinja = true

[Qwen3.8-27B:Q8_K_XL]
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL
ctx-size = 65536
np = 1
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 20
min-p = 0.0
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-effort = medium
repeat-penalty = 1.0
presence-penalty = 0

[Qwen3.8-27B:Q4_K_XL]
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL
ctx-size = 65536
np = 1
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 20
min-p = 0.0
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-effort = medium
repeat-penalty = 1.0
presence-penalty = 0

[Qwen3.8-27B:Q4_0]
hf = unsloth/Qwen3.8-27B-GGUF:Q4_0
ctx-size = 65536
np = 1
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 20
min-p = 0.0
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-effort = medium
repeat-penalty = 1.0
presence-penalty = 0

[Qwen3.8-27B:IQ4_XS]
hf = unsloth/Qwen3.8-27B-GGUF:UD-IQ4_XS
ctx-size = 65536
np = 1
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 20
min-p = 0.0
cache-type-k = q8_0
cache-type-v = q8_0
reasoning-effort = medium
repeat-penalty = 1.0
presence-penalty = 0

[Qwen3.8-27B:Q2_K_XL]
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q2_K_XL
ctx-size = 131072
np = 1
temp = 1
top-p = 0.95
top-k = 20
min-p = 0.0
cache-type-k = q8_0
cache-type-v = q8_0